name: Playwright Tests with Allure

on: 
  push:
    branches-ignore:
      - gh-pages

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: playwright/package-lock.json
      
      - name: Install dependencies
        working-directory: playwright
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: playwright
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        working-directory: playwright
        run: npm test
        continue-on-error: true
      
      - name: Install Java (required for Allure)
        uses: actions/setup-java@v4
        if: always()
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Install Allure CLI
        if: always()
        run: |
          curl -o allure-2.24.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version
      
      - name: Checkout gh-pages branch (for history)
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Copy Allure history
        if: always()
        run: |
          if [ -d "gh-pages/history" ]; then
            mkdir -p playwright/allure-results/history
            cp -r gh-pages/history/* playwright/allure-results/history/
          fi
      
      - name: Generate Allure Report
        if: always()
        run: |
          cd playwright
          allure generate allure-results --clean -o ../allure-report
      
      - name: Verify Allure Report Structure
        if: always()
        run: |
          echo "Checking allure-report directory structure:"
          ls -la allure-report/
          if [ ! -f "allure-report/index.html" ]; then
            echo "ERROR: index.html not found in allure-report!"
            exit 1
          fi
          echo "index.html found successfully"
      
      - name: Add .nojekyll file
        if: always()
        run: |
          touch allure-report/.nojekyll
          echo "Added .nojekyll file to prevent Jekyll processing"
      
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          keep_files: false
